# Generated by Django 4.1.1 on 2023-03-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='dddfgfhm', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
